name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore 'src/FeatureFlagFramework.sln'
    - name: Build FeatureFlagFramework.Core
      run: dotnet build 'src/FeatureFlagFramework.Core/FeatureFlagFramework.Core.csproj' --configuration Release --no-restore
    - name: Build FeatureFlagFramework.Clients.LaunchDarkly
      run: dotnet build 'src/FeatureFlagFramework.Clients.LaunchDarkly/FeatureFlagFramework.Clients.LaunchDarkly.csproj' --configuration Release --no-restore
    - name: Build FeatureFlagFramework.Clients.Featureflow
      run: dotnet build 'src/FeatureFlagFramework.Clients.Featureflow/FeatureFlagFramework.Clients.Featureflow.csproj' --configuration Release --no-restore
    - name: Publish FeatureFlagFramework.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/FeatureFlagFramework.Core/FeatureFlagFramework.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
